### ISSUE TITLE
PING swallows conf exception and only logs them. 

### ISSUE THREAD

**Issue by baranowb** [jgroups-extras/jgroups-azure#13]
https://github.com/jgroups-extras/jgroups-azure/blob/master/azure/src/main/java/org/jgroups/protocols/azure/AZURE_PING.java#L78

**Comment by rhusar** [comment]
Hm, I guess you are right, the exception should just propagate up.

Can you paste some logs what you configured and what happened?

**Comment by rhusar** [comment]
PR: https://github.com/jgroups-extras/jgroups-azure/pull/14
