### ISSUE TITLE
Add azure to groupId

### ISSUE THREAD

**Issue by slaskawi** [jgroups-extras/jgroups-azure#18]
Currently the group id that is used by Azure PING is `org.jgroups`. This doesn't scale :)

It would be much better to use `org.jgroups.azure` or something similar.

**Comment by rhusar** [comment]
@slaskawi I guess you are right. What should be the best here? `org.jgroups.azure` or `org.jgroups.azure.ping` ?

**Comment by slaskawi** [comment]
In `KUBE_PING` I used `<groupId>org.jgroups.kubernetes</groupId>` see [here](https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/pom.xml#L32).

**Comment by rhusar** [comment]
Ok, I will just use `org.jgroups.azure` then.

However, since you brought this up, instead the artifactId for kube is badly chosen, since that doesn't scale either https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/pom.xml#L33 :-/

**Comment by slaskawi** [comment]
Why is that?

**Comment by rhusar** [comment]
Any other possible project in org.jgroups.kubernetes group ID will be confused as to what "parent" is. 

e.g. compare to projects setup properly like https://github.com/wildfly/wildfly/blob/master/pom.xml#L33 or https://github.com/infinispan/infinispan/blob/master/pom.xml#L7

**Comment by slaskawi** [comment]
I'm not planning to do any other projects there...

Although there's a DNS_PING (which was specifically designed to work with
Kubernetes Headless Services) but I implemented it directly in JGroups:
https://github.com/belaban/JGroups/tree/master/src/org/jgroups/protocols/dns

**Comment by rhusar** [comment]
> I'm not planning to do any other projects there...

Well that's what I thought your original concern was about that it "does not scale" :-) even though there might not be ideas now, there might be later.

I have seen DNS_PING and it looks good!

**Comment by rhusar** [comment]
Done.
